image: maven:3.9.9

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

cache:
  paths:
    - .m2/repository

stages:
  - clean
  - package
  - deploy

clean:
  stage: clean
  script:
    - echo "Running clean stage"
    - mvn -B clean -e

package:
  stage: package
  script:
    - echo "Running package stage"
    - mvn -B package -e
  artifacts:
    paths:
    - target/*.jar

deploy:
  stage: deploy
  script:
    - echo "Starting deploy..."
    - mkdir -p "C:/Program Files/ProjetoIntegracao"
    - cp target/jfx/ProjectIntegration-1.0.exe "C:/Program Files/ProjetoIntegracao/"
    - echo "Deploy completed successfully"

