image: maven:3.9.9

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

cache:
  paths:
    - .m2/repository

stages:
  - clean
  - test
  - package
  - deploy

clean:
  stage: clean
  script:
    - echo "Running clean stage"
    - mvn -B clean -e

test:
  stage: test
  script:
    - echo "Running test stage"
    - mvn -B test -e

package:
  stage: package
  script:
    - echo "Running package stage"
    - mvn -B package -DskipTests -e
  artifacts:
    paths:
    - target/jfx/native/ProjectIntegration-1.0.exe

deploy:
  stage: deploy
  script:
    - echo "Starting deploy..."
    - Copy-Item -Path "target\jfx\native\ProjectIntegration-1.0.exe" -Destination "C:\Program Files\ProjetoIntegracao\GitLab" -Recurse -Force
    - echo "Deploy completed successfully"
  only:
    - feature/project-v5